version: '3.4'
name: FiapDocker
services:
  
# Banco de dados

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    # mem_limit: 3072M
    environment:
      SA_PASSWORD: "huaHhbSyjn9bttt"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - postech-network

  # Prometheus para coleta de métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - postech-network

  # Grafana para visualização de dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - postech-network

  # Gateway 
  kong-database:
    image: postgres:11.16
    container_name: kong-database
    restart: always
    environment:
      - POSTGRES_USER=${KONG_DB_USERNAME}
      - POSTGRES_PASSWORD=${KONG_DB_PASSWORD}
      - POSTGRES_DB=${KONG_DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - kong_pgdata:/var/lib/postgresql/data
    networks:
       - postech-network 

  kong-migrations:
    image: kong:3.4
    entrypoint: "kong migrations bootstrap"
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_DB_HOST}
      - KONG_PG_DATABASE=${KONG_DB_NAME}
      - KONG_PG_USER=${KONG_DB_USERNAME}
      - KONG_PG_PASSWORD=${KONG_DB_PASSWORD}
    restart: on-failure
    links:
      - kong-database
    networks:
       - postech-network 
    depends_on:
      - kong-database
    
  kong:
    image: kong:3.4
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_DB_HOST}
      - KONG_PG_DATABASE=${KONG_DB_NAME}
      - KONG_PG_USER=${KONG_DB_USERNAME}
      - KONG_PG_PASSWORD=${KONG_DB_PASSWORD}
      - KONG_LOG_LEVEL=${KONG_LOG_LEVEL}
      - KONG_PROXY_ACCESS_LOG=${KONG_PROXY_ACCESS_LOG}
      - KONG_ADMIN_ACCESS_LOG=${KONG_ADMIN_ACCESS_LOG}
      - KONG_PROXY_ERROR_LOG=${KONG_PROXY_ERROR_LOG}
      - KONG_ADMIN_ERROR_LOG=${KONG_ADMIN_ERROR_LOG}
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN}
      - KONG_ADMIN_GUI_URL=${KONG_ADMIN_GUI_URL}
    restart: always
    links:
      - kong-database
    ports:
      - ${KONG_PROXY_PORT}:${KONG_PROXY_PORT}
      - ${KONG_PROXY_SSL_PORT}:${KONG_PROXY_SSL_PORT}
      - ${KONG_PROXY_ADMIN_API_PORT}:${KONG_PROXY_ADMIN_API_PORT}
      - ${KONG_PROXY_ADMIN_SSL_API_PORT}:${KONG_PROXY_ADMIN_SSL_API_PORT}
      - ${KONG_MANAGER_PORT}:${KONG_MANAGER_PORT}
      - ${KONG_MANAGER_SSL_PORT}:${KONG_MANAGER_SSL_PORT}
      - ${KONG_3_PORT}:${KONG_3_PORT}
      - ${KONG_4_PORT}:${KONG_4_PORT}
    networks:
      - postech-network 
    depends_on:
      - kong-database
      - kong-migrations
  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga"
    restart: on-failure
    links:
      - kong-database
    networks:
      - postech-network 
    depends_on:
      - kong-database
      - kong-migrations
      - kong
  konga:
    image: pantsel/konga:latest
    environment:
      - TOKEN_SECRET=${KONGA_TOKEN_SECRET}
      - DB_ADAPTER=${KONG_DATABASE}
      - DB_HOST=${KONG_DB_HOST}
      - DB_PORT=${KONG_DB_PORT}
      - DB_DATABASE=${KONGA_DB_NAME}
      - DB_USER=${KONG_DB_USERNAME}
      - DB_PASSWORD=${KONG_DB_PASSWORD}
      - NODE_ENV=${KONGA_ENV}
    restart: always
    links:
      - kong-database
    ports:
      - ${KONGA_PORT}:${KONGA_PORT}
    networks:
      - postech-network 
    depends_on:
      - kong-database
      - kong-migrations
      - kong
      - konga-prepare
      
  #RabbitMq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # porta de conexão dos apps
      - "15672:15672" # porta da UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - postech-network
      
   # SonarQube   
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"       # Porta web do SonarQube
      - "9092:9092"       # Porta para sonar scanner (opcional)
    # environment:
      # - SONAR_JDBC_USERNAME=sonar
      # - SONAR_JDBC_PASSWORD=sonar
      # - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      # - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true  # Para evitar erro de memória
    # depends_on:
      # - db
    networks:
      - postech-network
    restart: unless-stopped

  # Elasticsearch para busca avançada de jogos
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - postech-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=10s || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Logstash para processamento e agregação de logs
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.4
    container_name: logstash
    ports:
      - "5044:5044"  # TCP input for Serilog (changed from 5000 to avoid conflict)
      - "9600:9600"  # Logstash monitoring API
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - postech-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Kibana para visualização do Elasticsearch  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - postech-network
    depends_on:
      elasticsearch:
        condition: service_healthy
      logstash:
        condition: service_healthy
    restart: unless-stopped

  # Jaeger para Distributed Tracing
  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger
    ports:
      - "14268:14268"  # Jaeger collector HTTP
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp"  # Jaeger agent UDP
      - "6832:6832/udp"  # Jaeger agent UDP  
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
    networks:
      - postech-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:16686/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  sql_data:
  prometheus_data:
  grafana_data:
  kong_pgdata:
  elasticsearch_data:
  
networks:
  postech-network:
    external: true